# Generated by Django 4.2.4 on 2023-09-03 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('release_date', models.DateField()),
                ('description', models.TextField()),
                ('cast', models.TextField()),
                ('trailer', models.FileField(upload_to='trailers/movies/')),
                ('video_file', models.FileField(upload_to='videos/movies/')),
                ('poster_path', models.ImageField(blank=True, null=True, upload_to='posters/movies/')),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('release_date', models.DateField()),
                ('poster_path', models.ImageField(blank=True, null=True, upload_to='posters/series/')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_number', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('cast', models.TextField()),
                ('trailer', models.FileField(upload_to='trailers/series/seasons/')),
                ('release_date', models.DateField()),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos_account.series')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('episode_number', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('video_file', models.FileField(upload_to='videos/series/seasons/')),
                ('release_date', models.DateField()),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos_account.season')),
            ],
        ),
    ]
